application: s~simpadaptest
version: 0.9
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /style
  static_dir: style

- url: /js
  static_dir: js

- url: /estim/admin/.*
  script: adaptest.app
  login: admin
    
- url: /.*
  script: adaptest.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

builtins:
- remote_api: on
